project:
  type: website
  output-dir: docs

execute: 
  freeze: true

website:
  title: "Meetup Burnout Minisite"
  google-analytics: "G-SKN5BS6ZBZ"
  description: "Minisite for my talk on meetup burnout"
  navbar:
    right:
      - talk/index.qmd
      - part1/index.qmd
      - part2/index.qmd
      - part3/index.qmd
  twitter-card: 
    card-style: summary
    creator: "@tladeras"
format:
  html:
    embed-resources: true
    link-external-icon: true
    link-external-newwindow: true
    theme: lux
    css: styles.css
